/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Kierunek;

public class KierunekData {

	private static Kierunek entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Kierunek newEntity = new Kierunek();
		newEntity.setNazwaKier( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setNazwaWydzialu( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        Kierunek managedEntity = (Kierunek) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Kierunek getEntity() {
    	return entity;
    }
}
