/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Ocena;

public class OcenaData {

	private static Ocena entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Ocena newEntity = new Ocena();
		newEntity.setIdOcena( 100 ) ;
		newEntity.setIdProwadz( 100 ) ;
		newEntity.setIdPrzedmiotu( 100 ) ;
		newEntity.setNrIndeksu( 100 ) ;
		newEntity.setOcena( (short)1 ) ;

		// save entity in database
        em.getTransaction().begin();
        Ocena managedEntity = (Ocena) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Ocena getEntity() {
    	return entity;
    }
}
