/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Prowadzacy;

public class ProwadzacyData {

	private static Prowadzacy entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Prowadzacy newEntity = new Prowadzacy();
		newEntity.setIdProwadz( 100 ) ;
		newEntity.setIdPrzedmiotu( Integer.valueOf(100) ) ;
		newEntity.setImie( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setNazwisko( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setEmailProwadzacego( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setNrTelefonu( Integer.valueOf(100) ) ;
		newEntity.setDataZatrudnienia( java.time.LocalDate.parse("2001-06-22") ) ;

		// save entity in database
        em.getTransaction().begin();
        Prowadzacy managedEntity = (Prowadzacy) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Prowadzacy getEntity() {
    	return entity;
    }
}
