/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Przedmiot;

public class PrzedmiotData {

	private static Przedmiot entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Przedmiot newEntity = new Przedmiot();
		newEntity.setIdPrzedmiotu( 100 ) ;
		newEntity.setNazwaKier( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setNazwaPrzedmiotu( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        Przedmiot managedEntity = (Przedmiot) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Przedmiot getEntity() {
    	return entity;
    }
}
