/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Student;

public class StudentData {

	private static Student entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Student newEntity = new Student();
		newEntity.setNrIndeksu( 100 ) ;
		newEntity.setImie( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setNazwisko( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setEmail( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		newEntity.setNrTelefonu( Integer.valueOf(100) ) ;
		newEntity.setDataRozpoczecia( java.time.LocalDate.parse("2001-06-22") ) ;
		newEntity.setDataZakonczenia( java.time.LocalDate.parse("2001-06-22") ) ;

		// save entity in database
        em.getTransaction().begin();
        Student managedEntity = (Student) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Student getEntity() {
    	return entity;
    }
}
