/*
 * Created on 2023-01-03 ( 08:34:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.StudentKierunek;

public class StudentKierunekData {

	private static StudentKierunek entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	StudentKierunek newEntity = new StudentKierunek();
		newEntity.setNrIndeksu( 100 ) ;
		newEntity.setNazwaKier( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        StudentKierunek managedEntity = (StudentKierunek) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static StudentKierunek getEntity() {
    	return entity;
    }
}
