/*
 * Created on 2023-01-03 ( 08:34:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.data;

import javax.persistence.EntityManager;

import org.demo.entities.Wydzial;

public class WydzialData {

	private static Wydzial entity ;

    public static void init(EntityManager em) {
    	// new entity instance
    	Wydzial newEntity = new Wydzial();
		newEntity.setNazwaWydzialu( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;

		// save entity in database
        em.getTransaction().begin();
        Wydzial managedEntity = (Wydzial) em.merge(newEntity);
        em.getTransaction().commit();
        entity = managedEntity;
    }
	
    public static Wydzial getEntity() {
    	return entity;
    }
}
