spring:
  datasource:
    password: 12345
    username: szrbd
    url: jdbc:postgresql://localhost:5432/dziennikocen
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
springdoc:
  api-docs:
    path: /dokumentacja