spring:
  datasource:
    password: inwester21
    username: postgres
    url: jdbc:postgresql://localhost:5433/dziennikocen
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
springdoc:
  api-docs:
    path: /dokumentacja