spring:
  datasource:
    password: inwester21
    username: szymon
    url: jdbc:postgresql://localhost:5433/dziennikocen
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

