spring:
  datasource:
    password: bdEZesDenNkHnlmyrWMkhHszOHiT8kmZ
    username: szymon
    url: jdbc:postgresql://dpg-ci3isj67avj2t32p2dmg-a.frankfurt-postgres.render.com:5432/dziennikocen
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
springdoc:
  api-docs:
    path: /dokumentacja