/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;
import static junit.framework.TestCase.assertNull;

import org.demo.jpa.tools.JpaTest;
import org.junit.Test;

public class KierunekJpaTest extends JpaTest {
	
    @Override
    public void initData() {
		// DatabaseData.init(em) has been called before
		// Initialize here other data required for the current test
    }
	
    private Kierunek createEntity() {
    	Kierunek entity = new Kierunek();
		entity.setNazwaKier( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setNazwaWydzialu( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }

    private Object getEntityKey(Kierunek entity) {
    	return entity.getNazwaKier();
    }

    @Test
    public void testPersistFindRemove() {
    	
    	Kierunek entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(Kierunek.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			Kierunek entity2 = find(Kierunek.class, key);
			assertNotNull(entity2);
        
			// Remove
			remove(entity2);
			assertNull(find(Kierunek.class, key));
		}
    }
    
    @Test
    public void testMergeFindRemove() {
    	
    	Kierunek entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	Kierunek entity2 = find(Kierunek.class, key);
        assertNotNull(entity2);
        
    	// Remove
    	remove(entity2);
        assertNull(find(Kierunek.class, key));
    }

}
