/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;
import static junit.framework.TestCase.assertNull;

import org.demo.jpa.tools.JpaTest;
import org.junit.Test;

public class OcenaJpaTest extends JpaTest {
	
    @Override
    public void initData() {
		// DatabaseData.init(em) has been called before
		// Initialize here other data required for the current test
    }
	
    private Ocena createEntity() {
    	Ocena entity = new Ocena();
		entity.setIdOcena( 200 ) ;
		entity.setIdProwadz( 200 ) ;
		entity.setIdPrzedmiotu( 200 ) ;
		entity.setNrIndeksu( 200 ) ;
		entity.setOcena( (short)2 ) ;
    	return entity;
    }

    private Object getEntityKey(Ocena entity) {
    	return entity.getIdOcena();
    }

    @Test
    public void testPersistFindRemove() {
    	
    	Ocena entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(Ocena.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			Ocena entity2 = find(Ocena.class, key);
			assertNotNull(entity2);
        
			// Remove
			remove(entity2);
			assertNull(find(Ocena.class, key));
		}
    }
    
    @Test
    public void testMergeFindRemove() {
    	
    	Ocena entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	Ocena entity2 = find(Ocena.class, key);
        assertNotNull(entity2);
        
    	// Remove
    	remove(entity2);
        assertNull(find(Ocena.class, key));
    }

}
