/*
 * Created on 2023-01-03 ( 08:34:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;
import static junit.framework.TestCase.assertNull;

import org.demo.jpa.tools.JpaTest;
import org.junit.Test;

public class StudentKierunekJpaTest extends JpaTest {
	
    @Override
    public void initData() {
		// DatabaseData.init(em) has been called before
		// Initialize here other data required for the current test
    }
	
    private StudentKierunek createEntity() {
    	StudentKierunek entity = new StudentKierunek();
		entity.setNrIndeksu( 200 ) ;
		entity.setNazwaKier( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }

    private Object getEntityKey(StudentKierunek entity) {
		return new StudentKierunekId( entity.getNrIndeksu(), entity.getNazwaKier() );
    }

    @Test
    public void testPersistFindRemove() {
    	
    	StudentKierunek entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(StudentKierunek.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			StudentKierunek entity2 = find(StudentKierunek.class, key);
			assertNotNull(entity2);
        
			// Remove
			remove(entity2);
			assertNull(find(StudentKierunek.class, key));
		}
    }
    
    @Test
    public void testMergeFindRemove() {
    	
    	StudentKierunek entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	StudentKierunek entity2 = find(StudentKierunek.class, key);
        assertNotNull(entity2);
        
    	// Remove
    	remove(entity2);
        assertNull(find(StudentKierunek.class, key));
    }

}
