/*
 * Created on 2023-01-03 ( 08:34:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.entities;

import static junit.framework.TestCase.assertNotNull;
import static junit.framework.TestCase.assertNull;

import org.demo.jpa.tools.JpaTest;
import org.junit.Test;

public class StudentJpaTest extends JpaTest {
	
    @Override
    public void initData() {
		// DatabaseData.init(em) has been called before
		// Initialize here other data required for the current test
    }
	
    private Student createEntity() {
    	Student entity = new Student();
		entity.setNrIndeksu( 200 ) ;
		entity.setImie( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setNazwisko( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setEmail( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setNrTelefonu( Integer.valueOf(200) ) ;
		entity.setDataRozpoczecia( java.time.LocalDate.parse("2002-06-22") ) ;
		entity.setDataZakonczenia( java.time.LocalDate.parse("2002-06-22") ) ;
    	return entity;
    }

    private Object getEntityKey(Student entity) {
    	return entity.getNrIndeksu();
    }

    @Test
    public void testPersistFindRemove() {
    	
    	Student entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(Student.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			Student entity2 = find(Student.class, key);
			assertNotNull(entity2);
        
			// Remove
			remove(entity2);
			assertNull(find(Student.class, key));
		}
    }
    
    @Test
    public void testMergeFindRemove() {
    	
    	Student entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	Student entity2 = find(Student.class, key);
        assertNotNull(entity2);
        
    	// Remove
    	remove(entity2);
        assertNull(find(Student.class, key));
    }

}
