/*
 * Created on 2023-01-03 ( 08:34:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.0.0
 */
package org.demo.jpa.tools;

import jakarta.persistence.EntityManager;

import org.demo.jpa.data.KierunekData;
import org.demo.jpa.data.OcenaData;
import org.demo.jpa.data.ProwadzacyData;
import org.demo.jpa.data.PrzedmiotData;
import org.demo.jpa.data.StudentData;
import org.demo.jpa.data.StudentKierunekData;
import org.demo.jpa.data.WydzialData;

/**
 * Database initialization before unit tests
 * 
 * @author Telosys
 *
 */
public class DatabaseInit {

    public static void init(EntityManager em) {

		// Disable referential integrity
    	em.getTransaction().begin();
    	em.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();
    	em.getTransaction().commit();

		// Init data for all entities
		KierunekData.init(em);
		OcenaData.init(em);
		ProwadzacyData.init(em);
		PrzedmiotData.init(em);
		StudentData.init(em);
		StudentKierunekData.init(em);
		WydzialData.init(em);

		// Enable referential integrity
    	em.getTransaction().begin();
    	em.createNativeQuery("SET REFERENTIAL_INTEGRITY TRUE").executeUpdate();
    	em.getTransaction().commit();
    }

}
